name: Node.js CI/CD

on:
  push:
    branches: [ "main" ] # Триггер на push в ветку main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # Используем Ubuntu

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Укажите нужную версию Node.js

      - name: Install dependencies
        run: npm install

      - name: Build (если используется сборка, например, TypeScript/Babel)
        run: npm run build # Если есть скрипт build в package.json

      #      - name: Run tests (опционально)
      #        run: npm test # Если есть тесты

      # Шаг для настройки SSH-ключа с паролем
      - name: Set up SSH key with passphrase
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

        # Проверка формата ключа
          ssh-keygen -l -f ~/.ssh/id_rsa

        # Создаем файл для автоматического ввода пароля
          echo -e "#!/bin/bash\n\necho $SSH_PASSPHRASE" > ~/.ssh/askpass.sh
          chmod +x ~/.ssh/askpass.sh

        # Устанавливаем переменную окружения SSH_ASKPASS
          export SSH_ASKPASS=~/.ssh/askpass.sh

        # Перезапуск ssh-agent (для гарантии, что агент чистый)
          eval $(ssh-agent -k) # Убиваем старый ssh-agent
          eval $(ssh-agent -s)  # Запускаем новый ssh-agent

        # Добавляем ключ в ssh-agent
          ssh-add ~/.ssh/id_rsa
          
        # Настройка для игнорирования предупреждений о недоверенных хостах
          mkdir -p ~/.ssh
          echo -e "Host *\n  StrictHostKeyChecking no\n  UserKnownHostsFile /dev/null" > ~/.ssh/config

      # Деплой (зависит от вашего сервера)
      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd dezoserver
            git pull origin main
            # npm install --production # Если нужно установить зависимости
            # pm2 restart my-app # Если используете PM2
